# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-26 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
